"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, CheckCircle2, Clock3, Download, ExternalLink, FileText, Inbox, LoaderCircle, Mail, MonitorUp, Paperclip, Pause, Play, RefreshCw, Search, Send, ShieldCheck, Sparkles, UserRound, UsersRound } from "lucide-react";

const PORTAL_URL="/agent-onboarding-portal/index.html",PARENT_SOURCE="finlead-onboarding-lab",STEP_DELAY=3800;
const CANDIDATE={name:"Riya Mehta",email:"riya.mehta@example.com",mobile:"98765 43210",pan:"ABCDE1234F",aadhaar:"4827 1936 5204",education:"B.Com",location:"Mumbai West"};
const FLOW=[
 ["INTEREST_RECEIVED","Interest received","inbound","Interested in becoming a POSP agent","Hello team, I would like to join your POSP network. I work with tax and renewal customers in Mumbai and would like to understand the onboarding process.",[]],
 ["DETAILS_REQUESTED","Details requested","outbound","Complete your insurance agent application","Thank you for your interest. Please reply with your personal, address, education, bank and prior-agency details, together with the documents listed below.",["Agent application checklist.pdf"]],
 ["DETAILS_RECEIVED","Details received","inbound","Re: Complete your insurance agent application","Please find my completed details and KYC documents attached. Let me know if anything else is required.",["PAN_Riya_Mehta.pdf","Aadhaar_Riya_Mehta.pdf","Passport_photo.jpg","Address_proof.pdf","BCom_certificate.pdf","Cancelled_cheque.pdf"]],
 ["FORM_1A_PREFILLED_SENT","Form 1A prefilled and sent","outbound","Action required: sign your prefilled Form 1A","We have validated your information and prepared Form 1A. Please review, sign and reply on this email thread.",["Form_1A_Riya_Mehta_prefilled.pdf"]],
 ["FORM_1A_SIGNED_RECEIVED","Signed Form 1A received","inbound","Re: Signed Form 1A attached","I have reviewed and signed Form 1A. The completed copy is attached.",["Form_1A_Riya_Mehta_signed.pdf"]],
 ["READY_FOR_INTERNAL_EVALUATION","Ready for evaluation","agent","Application pack validated","All 12 mandatory fields, six KYC documents and the signed declaration passed validation.",[]],
 ["PASSED_INTERNAL_EVALUATION","Evaluation passed","agent","Internal evaluation completed","Identity, prior association, candidate fit and conflict checks passed with no exception.",[]],
 ["TRAINING_INVITE_SENT","Training invite sent","outbound","Your mandatory POSP training access","Your 15-hour POSP learning path is ready. Use the credentials below and complete every module before the due date.",["Training_schedule.pdf"]],
 ["WAITING_TRAINING_CERTIFICATE","Waiting for training certificate","agent","Training completion being monitored","Atrium is waiting for the candidate to complete the course and return the certificate.",[]],
 ["TRAINING_CERTIFICATE_RECEIVED","Training certificate received","inbound","Re: POSP training certificate","I have completed the assigned learning modules. Please find my certificate attached.",["POSP_training_certificate.pdf"]],
 ["BRANCH_OFFICE_REVIEW_PENDING","Branch review pending","outbound","Approval required: Riya Mehta · POSP onboarding","Please review the attached candidate pack and reply with approve, reject, or clarification required.",["Riya_Mehta_application_pack.zip","Evaluation_summary.pdf"]],
 ["BRANCH_OFFICE_APPROVED","Branch office approved","inbound","Approved: Riya Mehta · POSP onboarding","Mumbai West branch approves this appointment with no conditions.",["Branch_approval_note.pdf"]],
 ["PORTAL_REGISTRATION_STARTED","III portal registration started","portal","Opening secure portal session","The approved application is being entered into the III portal field by field.",[],"REGISTER"],
 ["URN_GENERATED","URN generated","portal","Registration submitted","URN-IC38-20260904-104218 was generated and saved to the case.",[]],
 ["WAITING_SLOT_SELECTION","Waiting for slot selection","outbound","Choose your IC 38 examination slot","Please reply with your preferred exam date, time and centre from the available options.",["Available_exam_slots.pdf"]],
 ["SLOT_RECEIVED","Slot received","inbound","Re: IC 38 slot preference","My preference is 12 September 2026, 10:00 AM, Mumbai Central.",[]],
 ["EXAM_FEE_PAYMENT_PENDING","Exam fee payment pending","agent","Preparing exam payment","The selected slot is held while the ₹550 examination fee is prepared.",[]],
 ["EXAM_FEE_PAID","Exam fee paid","portal","Payment confirmed","₹550 payment confirmed with reference PAY-IC38-9042.",[],"BOOK_EXAM"],
 ["SLOT_BOOKED","Exam slot booked","portal","Booking confirmed","12 Sep 2026 · 10:00 AM · Mumbai Central · BKG-IC38-9042.",[]],
 ["HALL_TICKET_SENT","Hall ticket generated and sent","outbound","Your IC 38 hall ticket · 12 September","Your hall ticket, exam instructions and centre details are attached.",["Hall_Ticket_HT-IC38-260912-1842.pdf","Exam_day_instructions.pdf"],"HALL_TICKET"],
 ["WAITING_EXAM_RESULT","Waiting for exam result","agent","Result monitoring started","Atrium is checking the III portal against the candidate URN at scheduled intervals.",[],"WAIT_RESULT"],
 ["EXAM_RESULT_RECEIVED","Exam result retrieved","portal","Result published","Score 42/50 · PASS · identity and URN matched.",[],"RESULT"],
 ["EXAM_PASSED","Exam passed","agent","Candidate qualified","The passing result cleared the final activation gate.",[]],
 ["ONBOARDING_COMPLETED","Onboarding completed","outbound","Welcome to the network · your agent code is active","Your agent code POSP-MH-261842 is active. Portal credentials, mentor details and your first 30-day plan are attached.",["Agent_activation_letter.pdf","First_30_day_plan.pdf"],"COMPLETE"]
];
const TRACK_GROUPS=[
 ["Intake & documents",FLOW.slice(0,7).map(x=>x[0])], ["Training & branch",FLOW.slice(7,12).map(x=>x[0])],
 ["Portal & exam",FLOW.slice(12,20).map(x=>x[0])], ["Result & activation",FLOW.slice(20).map(x=>x[0])]
];
const OTHER_CASES=[{id:"arjun",name:"Arjun Sen",email:"arjun.sen@example.com",index:8,status:"Waiting for training certificate"},{id:"devika",name:"Devika Rao",email:"devika.rao@example.com",index:23,status:"Onboarding completed"}];
const emailDirection=x=>x[2]==="inbound"||x[2]==="outbound";

function EmailDetail({message,onStart,started}){if(!message)return <div className="ao-mail-empty"><Mail size={28}/><h3>Select a message</h3><p>Open an email to see the full thread and attachments.</p></div>;const inbound=message[2]==="inbound";return <article className="ao-mail-detail"><header><div className={inbound?"inbound":"outbound"}>{inbound?<Inbox size={17}/>:<Send size={17}/>}</div><div><h2>{message[3]}</h2><p>{inbound?`${CANDIDATE.name} <${CANDIDATE.email}>`:`FinLead Onboarding <onboarding@finlead.ai>`}</p></div><span>{inbound?"Received":"Sent"} · just now</span></header><div className="ao-mail-meta"><span>To</span><strong>{inbound?"onboarding@finlead.ai":CANDIDATE.email}</strong></div><div className="ao-mail-body"><p>Dear {inbound?"Onboarding Team":"Riya"},</p><p>{message[4]}</p><p>Best regards,<br/>{inbound?CANDIDATE.name:"The Insurance Onboarding Team"}</p></div>{message[5].length>0&&<div className="ao-attachments"><h3><Paperclip size={14}/>{message[5].length} attachment{message[5].length>1?"s":""}</h3><div>{message[5].map(file=><button key={file}><FileText size={16}/><span><strong>{file}</strong><small>Verified attachment</small></span><Download size={14}/></button>)}</div></div>}{message[0]==="INTEREST_RECEIVED"&&!started&&<footer><button className="ao-btn" onClick={onStart}><Sparkles size={16}/> Start onboarding from this email</button></footer>}</article>}

function Tracker({liveIndex,selectedCase,setSelectedCase}){const cases=[{id:"riya",name:CANDIDATE.name,email:CANDIDATE.email,index:Math.max(0,liveIndex),status:FLOW[Math.max(0,liveIndex)][1]},...OTHER_CASES],active=cases.find(x=>x.id===selectedCase)||cases[0],progress=Math.round((active.index+1)/FLOW.length*100);return <div className="ao-tracker"><aside><div className="ao-track-title"><h3>Onboarding cases</h3><span>{cases.length}</span></div>{cases.map(c=><button key={c.id} className={c.id===active.id?"active":""} onClick={()=>setSelectedCase(c.id)}><span>{c.name.split(" ").map(x=>x[0]).join("")}</span><div><strong>{c.name}</strong><small>{c.status}</small></div><b>{Math.round((c.index+1)/FLOW.length*100)}%</b></button>)}</aside><section><header><div><h2>{active.name}</h2><p>{active.email} · Case FL-AO-{active.id==="riya"?"260904":active.id==="arjun"?"260817":"260731"}</p></div><span>{progress}% complete</span></header><div className="ao-track-progress"><span style={{transform:`scaleX(${progress/100})`}}/></div><div className="ao-track-groups">{TRACK_GROUPS.map(([label,ids])=><section key={label}><h3>{label}</h3><div>{ids.map(id=>{const index=FLOW.findIndex(x=>x[0]===id),done=index<=active.index,current=index===active.index;return <article key={id} className={done?current?"current":"done":""}><span>{done&&!current?<Check size={13}/>:current&&active.id==="riya"&&liveIndex<FLOW.length-1?<LoaderCircle className="ao-spin" size={13}/>:index+1}</span><div><strong>{FLOW[index][1]}</strong><small>{done?current?"Current checkpoint":"Completed":"Not reached"}</small></div></article>})}</div></section>)}</div></section></div>}

export default function AgentOnboardingPlayground(){
 const [view,setView]=useState("email"),[flowIndex,setFlowIndex]=useState(-1),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[selectedMail,setSelectedMail]=useState(0),[selectedCase,setSelectedCase]=useState("riya"),[portalReady,setPortalReady]=useState(false);const iframeRef=useRef(null);
 const visible=FLOW.slice(0,Math.max(1,flowIndex+1)),emails=visible.filter(emailDirection),current=FLOW[Math.max(0,flowIndex)],progress=flowIndex<0?0:Math.round((flowIndex+1)/FLOW.length*100),lastPortalCommand=FLOW.slice(0,flowIndex+1).map(step=>step[6]).filter(Boolean).at(-1);
 useEffect(()=>{if(!running||paused||flowIndex>=FLOW.length-1)return;const timer=setTimeout(()=>setFlowIndex(i=>i+1),flowIndex<0?1200:STEP_DELAY);return()=>clearTimeout(timer)},[running,paused,flowIndex]);
 useEffect(()=>{if(flowIndex<0)return;const command=FLOW[flowIndex][6];if(command){iframeRef.current?.contentWindow?.postMessage({source:PARENT_SOURCE,type:command,payload:{candidate:CANDIDATE}},window.location.origin);if(command==="REGISTER")setView("portal")}if(flowIndex===FLOW.length-1)setRunning(false)},[flowIndex]);
 useEffect(()=>{setSelectedMail(Math.max(0,emails.length-1))},[emails.length]);
 const start=()=>{setFlowIndex(0);setRunning(true);setPaused(false)};const reset=()=>{setFlowIndex(-1);setRunning(false);setPaused(false);setView("email");setSelectedMail(0);iframeRef.current?.contentWindow?.postMessage({source:PARENT_SOURCE,type:"RESET"},window.location.origin)};
 return <main className="cq-root ao-root"><header className="cq-topbar"><a href="/" aria-label="FinLead AI home"><img src="/FinLeadAILogo.png" alt="FinLead AI"/></a><span>Playground</span></header><div className="cq-page"><a className="cq-back" href="/playground"><ArrowLeft size={16}/> Back to playground</a><div className="ao-page-head"><div className="cq-title"><h1>Agent Onboarding Automation</h1><p>Email-led onboarding with document collection, branch review, III portal automation, IC 38 examination and live case tracking.</p></div><div className="ao-page-actions">{flowIndex>=0&&flowIndex<FLOW.length-1&&<button className="ao-btn ao-btn-outline" onClick={()=>setPaused(x=>!x)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?"Resume":"Pause"}</button>}<button className="ao-btn ao-btn-outline" onClick={reset}><RefreshCw size={16}/> Reset demo</button></div></div>
 <section className="ao-command"><div><span className={flowIndex===FLOW.length-1?"complete":running&&!paused?"running":""}>{flowIndex===FLOW.length-1?<CheckCircle2 size={16}/>:running&&!paused?<LoaderCircle className="ao-spin" size={16}/>:<Clock3 size={16}/>}</span><div><h2>{flowIndex<0?"New candidate email received":current[1]}</h2><p>Riya Mehta · FL-AO-260904 · {flowIndex<0?"Ready to start":paused?"Automation paused":`${progress}% complete · next checkpoint in about ${STEP_DELAY/1000} seconds`}</p></div></div><div className="ao-command-progress"><span style={{transform:`scaleX(${progress/100})`}}/></div></section>
 <nav className="ao-view-tabs" aria-label="Onboarding views"><button className={view==="email"?"active":""} onClick={()=>setView("email")}><Mail size={16}/> Email inbox <span>{emails.length}</span></button><button className={view==="portal"?"active":""} onClick={()=>setView("portal")}><MonitorUp size={16}/> Portal automation <i className={portalReady?"online":""}/></button><button className={view==="tracker"?"active":""} onClick={()=>setView("tracker")}><UsersRound size={16}/> Onboarding tracker <span>3</span></button></nav>
 <div className="ao-views">{view==="email"?<div className="ao-mailbox"><aside><div className="ao-inbox-head"><div><h2>Agent onboarding</h2><p>Shared inbox</p></div><button aria-label="Search inbox"><Search size={15}/></button></div><div className="ao-mail-list">{emails.map((mail,index)=>{const inbound=mail[2]==="inbound";return <button key={`${mail[0]}-${index}`} className={index===selectedMail?"active":""} onClick={()=>setSelectedMail(index)}><span className={inbound?"inbound":"outbound"}>{inbound?<Inbox size={14}/>:<Send size={14}/>}</span><div><div><strong>{inbound?CANDIDATE.name:"FinLead Onboarding"}</strong><small>just now</small></div><h3>{mail[3]}</h3><p>{mail[4]}</p>{mail[5].length>0&&<b><Paperclip size={11}/>{mail[5].length}</b>}</div></button>})}</div></aside><EmailDetail message={emails[selectedMail]} onStart={start} started={flowIndex>=0}/></div>:view==="portal"?<div className="ao-portal-view"><div className="ao-browser-bar"><span><ShieldCheck size={16}/></span><div><strong>Insurance Institute Agent Services</strong><small>Secure embedded session · controlled by FinLead AI</small></div><div className="ao-connected"><i className={portalReady?"ready":""}/>{portalReady?"Connected":"Connecting"}</div><a href={PORTAL_URL} target="_blank" rel="noreferrer" aria-label="Open portal in a new tab"><ExternalLink size={16}/></a></div><div className="ao-browser-body"><iframe ref={iframeRef} src={PORTAL_URL} title="Insurance Institute agent onboarding portal" onLoad={()=>{setPortalReady(true);if(lastPortalCommand)setTimeout(()=>iframeRef.current?.contentWindow?.postMessage({source:PARENT_SOURCE,type:lastPortalCommand,payload:{candidate:CANDIDATE}},window.location.origin),100)}}/></div></div>:<Tracker liveIndex={Math.max(0,flowIndex)} selectedCase={selectedCase} setSelectedCase={setSelectedCase}/>}</div>
 </div></main>
}
